extends: ../cyst.yaml

project:
  name: cyst_2d_r2unet

model:
  name: r2unet
  type: 2D
  backbone: recurrent_residual_unet_encoder
  in_channels: auto
  num_classes: 2
  args:
    __replace__: true
    feature_channels: [32, 64, 128, 256, 512]
    recurrent_steps: 2

training:
  epochs: 60
  batch_size: 8
  image_size: [256, 256, 64]
  loss: ce_dice

k_fold:
  enabled: false

evaluation:
  evaluate_2d_as_volume: true
  batch_size: 1
  slice_batch_size: 8

