extends: ../cyst.yaml

project:
  name: cyst_2d_unet_resnet152

model:
  name: unet_resnet152
  type: 2D
  backbone: resnet152
  in_channels: auto
  num_classes: 2
  args:
    __replace__: true
    normalization: batchnorm
    # true: dung/tai ImageNet pretrained; false: train tu dau.
    encoder_pretrained: true

training:
  epochs: 60
  batch_size: 8
  image_size: [256, 256, 64]
  loss: ce_dice

k_fold:
  enabled: false

evaluation:
  evaluate_2d_as_volume: true
  batch_size: 1
  slice_batch_size: 8

