extends: ../cyst.yaml

project:
  name: cyst_2d_unetr

model:
  name: unetr
  type: 2D
  backbone: vit_encoder
  in_channels: auto
  num_classes: 2
  args:
    __replace__: true
    embed_dim: 384
    patch_size: 16
    num_heads: 6
    num_layers: 12
    mlp_dim: 1536
    dropout: 0.1

training:
  epochs: 60
  batch_size: 8
  image_size: [256, 256, 64]
  loss: ce_dice

k_fold:
  enabled: false

evaluation:
  evaluate_2d_as_volume: true
  batch_size: 1
  slice_batch_size: 8

